### Pobierz wszystkie zadania (GET)
GET http://localhost:8080/tasks

### Stwórz nowe zadanie (POST)
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "name": "Fix Critical Login Bug",
  "date": "2025-01-26",
  "priority": "HIGH",
  "status": "IN_PROGRESS",
  "subtasks": [
    {
      "name": "Reproduce the bug in staging environment",
      "completed": true
    },
    {
      "name": "Analyze server logs for error 500",
      "completed": true
    },
    {
      "name": "Apply fix to authentication service",
      "completed": false
    },
    {
      "name": "Write unit tests for the fix",
      "completed": false
    }
  ]
}

### Usuń zadanie (DELETE)
DELETE http://localhost:8080/tasks/4

### Zaaktualizuj zadanie (PUT)
PUT http://localhost:8080/tasks/3
Content-Type: application/json

{
  "name": "Integrate Payment Gateway (DONE)",
  "status": "COMPLETED",
  "priority": "MEDIUM",
  "subtasks": []
}